Redact GitHub access token
bitrise-steplib/steps-carthage pull request #51
Opened 2018-12-07 15:12 UTC by lszucs

Carthage step: GithubAccessToken input value is exposed in the log: https://app.clickup.com/t/bcg0c

2018-12-07 16:09 UTC, godrei commented on main.go
> +	CarthageCommand   string          `env:"carthage_command"`
is not it required?

2018-12-12 13:46 UTC, trapacska requested changes
please see my notes

2018-12-12 13:46 UTC, trapacska commented on bitrise.yml
> +        - github_access_token: $GITHUB_ACCESS_TOKEN
this is the default in step.yml as well, it is not necessary to set again

2018-12-14 14:43 UTC, godrei approved these changes

2018-12-14 14:46 UTC, trapacska approved these changes

2018-12-14 14:46 UTC, merged