Add ability to point to point to custom xcconfig via env var (Xcode 12 workaround)
bitrise-steplib/steps-carthage pull request #62
Opened 2020-09-21 23:56 UTC by maxmamis

There is a major known issue (https://github.com/Carthage/Carthage/issues/3019) building dependencies with Carthage using Xcode 12, and the best current workaround (https://github.com/Carthage/Carthage/issues/3019#issuecomment-693302447) involves specifying a custom `.xcconfig` file via an environment variable. 

This PR updates the Carthage Bitrise step to be compatible with this workaround, by adding the ability to specify a `.xcconfig` file to be added to the environment. 

This PR will also address this issue: https://github.com/bitrise-steplib/steps-carthage/issues/60

2020-09-24 17:03 UTC, Monte9 approved these changes
This is something we are running into as well. _I think_ this would help us, but I'll follow up here if we find another workaround.

2020-09-24 17:30 UTC, TizianoCoroneo approved these changes

2020-09-25 15:15 UTC, Monte9 requested changes
Actually, this PR doesn't seem to be needed at all. We solved this pretty easily (after hours of banging our heads against it)

Basically, all you need to do is to add `XCODE_XCCONFIG_FILE` under the `Env Var` section on Bitrise and it will automatically add it to the environment and Carthage will pick up on that config file.

<img width="982" alt="Screen Shot 2020-09-25 at 8 41 19 PM" src="https://user-images.githubusercontent.com/7840686/94284205-ab61fd80-ff6f-11ea-8eca-5185744179a6.png">

Give this a shot and if it works, we can lose out this PR as it's not needed!

2020-10-14 10:52 UTC, adborbas commented
Hi @maxmamis, @Monte9 ,

Thanks for the PR and the suggested workaround as well!

We have decided to resolve this by introducing a new step input as @maxmamis has suggested which can handle both local and remote files. Additionally, we will support setting the  `XCODE_XCCONFIG_FILE ` as well to keep supporting the workaround. If both are provided we will fallback to the step input and display a warning. I will close this PR as we will create a separate one.

2020-10-14 10:52 UTC, closed without merging